Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/cuda-python-docs/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/miniconda3/envs/cuda-python-docs/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/cuda-python-docs/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/cuda-python-docs/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/cuda-python-docs/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/miniconda3/envs/cuda-python-docs/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/miniconda3/envs/cuda-python-docs/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load PTX as module data and retrieve function
ptx = np.char.array(ptx)
# Note: Incompatible --gpu-architecture would be detected here
module = checkCudaErrors(driver.cuModuleLoadData(ptx.ctypes.data))
kernel = checkCudaErrors(driver.cuModuleGetFunction(module, b"saxpy"))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[6], line 4[0m
[1;32m      2[0m ptx [38;5;241m=[39m np[38;5;241m.[39mchar[38;5;241m.[39marray(ptx)
[1;32m      3[0m [38;5;66;03m# Note: Incompatible --gpu-architecture would be detected here[39;00m
[0;32m----> 4[0m module [38;5;241m=[39m [43mcheckCudaErrors[49m[43m([49m[43mdriver[49m[38;5;241;43m.[39;49m[43mcuModuleLoadData[49m[43m([49m[43mptx[49m[38;5;241;43m.[39;49m[43mctypes[49m[38;5;241;43m.[39;49m[43mdata[49m[43m)[49m[43m)[49m
[1;32m      5[0m kernel [38;5;241m=[39m checkCudaErrors(driver[38;5;241m.[39mcuModuleGetFunction(module, [38;5;124mb[39m[38;5;124m"[39m[38;5;124msaxpy[39m[38;5;124m"[39m))

Cell [0;32mIn[2], line 12[0m, in [0;36mcheckCudaErrors[0;34m(result)[0m
[1;32m     10[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mcheckCudaErrors[39m(result):
[1;32m     11[0m     [38;5;28;01mif[39;00m result[[38;5;241m0[39m][38;5;241m.[39mvalue:
[0;32m---> 12[0m         [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m"[39m[38;5;124mCUDA error code=[39m[38;5;132;01m{}[39;00m[38;5;124m([39m[38;5;132;01m{}[39;00m[38;5;124m)[39m[38;5;124m"[39m[38;5;241m.[39mformat(result[[38;5;241m0[39m][38;5;241m.[39mvalue, _cudaGetErrorEnum(result[[38;5;241m0[39m])))
[1;32m     13[0m     [38;5;28;01mif[39;00m [38;5;28mlen[39m(result) [38;5;241m==[39m [38;5;241m1[39m:
[1;32m     14[0m         [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m

[0;31mRuntimeError[0m: CUDA error code=222(b'CUDA_ERROR_UNSUPPORTED_PTX_VERSION')

